// <auto-generated />
using System;
using Bank_Account_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank_Account_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825153712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank_Account_API.Models.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("BankId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountHolderName = "Thillai Shanmugam",
                            AccountNumber = "100010001001",
                            AccountType = "Savings",
                            Balance = 50000.00m,
                            BankId = 1
                        },
                        new
                        {
                            AccountId = 2,
                            AccountHolderName = "Tamilvani",
                            AccountNumber = "200020002002",
                            AccountType = "Savings",
                            Balance = 75000.00m,
                            BankId = 2
                        },
                        new
                        {
                            AccountId = 3,
                            AccountHolderName = "Dharshini",
                            AccountNumber = "300030003003",
                            AccountType = "Current",
                            Balance = 60000.00m,
                            BankId = 3
                        },
                        new
                        {
                            AccountId = 4,
                            AccountHolderName = "Abinaya",
                            AccountNumber = "400040004004",
                            AccountType = "Savings",
                            Balance = 90000.00m,
                            BankId = 4
                        });
                });

            modelBuilder.Entity("Bank_Account_API.Models.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("BankId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = 1,
                            Address = "Mumbai, Maharashtra",
                            BankName = "State Bank of India",
                            BranchCode = "SBI001",
                            IFSCCode = "SBIN0000001"
                        },
                        new
                        {
                            BankId = 2,
                            Address = "Mumbai, Maharashtra",
                            BankName = "HDFC Bank",
                            BranchCode = "HDFC01",
                            IFSCCode = "HDFC0000001"
                        },
                        new
                        {
                            BankId = 3,
                            Address = "Mumbai, Maharashtra",
                            BankName = "ICICI Bank",
                            BranchCode = "ICICI1",
                            IFSCCode = "ICIC0000001"
                        },
                        new
                        {
                            BankId = 4,
                            Address = "Mumbai, Maharashtra",
                            BankName = "Axis Bank",
                            BranchCode = "AXIS01",
                            IFSCCode = "UTIB0000001"
                        },
                        new
                        {
                            BankId = 5,
                            Address = "New Delhi, Delhi",
                            BankName = "Punjab National Bank",
                            BranchCode = "PNB001",
                            IFSCCode = "PUNB0000001"
                        });
                });

            modelBuilder.Entity("Bank_Account_API.Models.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountId = 1,
                            Amount = 10000.00m,
                            Description = "Initial Deposit",
                            TransactionDate = new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Credit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountId = 1,
                            Amount = 2000.00m,
                            Description = "ATM Withdrawal",
                            TransactionDate = new DateTime(2026, 8, 22, 14, 30, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Debit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountId = 2,
                            Amount = 15000.00m,
                            Description = "Salary Credit",
                            TransactionDate = new DateTime(2026, 8, 21, 11, 15, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Credit"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountId = 3,
                            Amount = 5000.00m,
                            Description = "Online Shopping",
                            TransactionDate = new DateTime(2026, 8, 23, 9, 45, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Debit"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountId = 4,
                            Amount = 25000.00m,
                            Description = "Funds Transfer",
                            TransactionDate = new DateTime(2026, 8, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = "Credit"
                        });
                });

            modelBuilder.Entity("Bank_Account_API.Models.Accounts", b =>
                {
                    b.HasOne("Bank_Account_API.Models.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Bank_Account_API.Models.Transactions", b =>
                {
                    b.HasOne("Bank_Account_API.Models.Accounts", "Accounts")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Bank_Account_API.Models.Accounts", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Bank_Account_API.Models.Bank", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
